name: iban-calculator-scraper
region: nyc1
services:
- name: api
  source_dir: /
  github:
    repo: dammyaro/iban-scraper
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  build_command: |
    echo "Building optimized IBAN scraper for Digital Ocean..."
    echo "Using Python 3.11 for better compatibility..."
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 65
  environment_slug: docker
  instance_count: 1
  instance_size_slug: basic-s  # 1 vCPU, 512MB RAM - needed for Playwright
  http_port: 8000
  
  health_check:
    http_path: /health
    initial_delay_seconds: 90  # Increased for Playwright browser installation
    period_seconds: 30
    timeout_seconds: 15
    failure_threshold: 3
    success_threshold: 1
  
  envs:
  - key: PYTHONPATH
    value: /home/app
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PLAYWRIGHT_HEADLESS
    value: "true"
  - key: PLAYWRIGHT_TIMEOUT
    value: "30000"
  - key: DISABLE_PLAYWRIGHT
    value: "false"
  - key: PLAYWRIGHT_BROWSERS_PATH
    value: "/ms-playwright"
  
  # Optimized auto-scaling for cost efficiency
  autoscaling:
    min_instance_count: 1
    max_instance_count: 2
    metrics:
    - type: cpu
      target:
        average_utilization: 80
    - type: memory
      target:
        average_utilization: 85

# Optional: Redis for caching IBAN results (commented out for cost optimization)
# databases:
# - name: redis-cache
#   engine: REDIS
#   version: "7"
#   size: db-s-1vcpu-1gb