name: iban-wise-calculator
region: nyc1
services:
- name: iban-api
  source_dir: /
  github:
    repo: dammyaro/iban-scraper
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  build_command: |
    echo "Building IBAN Calculator with Wise integration..."
    echo "Version 3.1.0 - Playwright + Bank Name Extraction"
  run_command: uvicorn main_fixed:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 65
  environment_slug: docker
  instance_count: 1
  instance_size_slug: basic-s  # 1 vCPU, 512MB RAM - sufficient for Playwright
  http_port: 8000
  
  health_check:
    http_path: /health
    initial_delay_seconds: 120  # Extra time for Playwright browser installation
    period_seconds: 30
    timeout_seconds: 20
    failure_threshold: 3
    success_threshold: 1
  
  envs:
  - key: PYTHONPATH
    value: /home/app
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PLAYWRIGHT_HEADLESS
    value: "true"
  - key: PLAYWRIGHT_TIMEOUT
    value: "60000"
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: "8000"
  
  # Cost-optimized auto-scaling
  autoscaling:
    min_instance_count: 1
    max_instance_count: 2
    metrics:
    - type: cpu
      target:
        average_utilization: 75
    - type: memory
      target:
        average_utilization: 80